# https://taskfile.dev

version: "3"

includes:
  1-infra:
    taskfile: ./1-infra
    dir: ./1-infra
  2-gitlab_config:
    taskfile: ./2-gitlab_config
    dir: ./2-gitlab_config

tasks:
  init:
    desc: Run terraform init
    cmds:
      - task: 1-infra:init
      - task: 2-gitlab_config:init

  plan:
    desc: Run terraform plan
    cmds:
      - task: 1-infra:plan
      - task: 2-gitlab_config:plan

  apply:
    desc: Run terraform apply
    cmds:
      - task: 1-infra:apply
      - task: 2-gitlab_config:apply

  destroy:
    desc: Run terraform destroy
    cmds:
      - task: 2-gitlab_config:destroy
      - task: 1-infra:destroy
